{{- if and .Values.rbac.create (eq (include "argocd-clusterprofile-controller.watchesAllClusterProfiles" .) "true") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "argocd-clusterprofile-controller.clusterProfileClusterRoleName" . }}
  labels:
    {{- include "argocd-clusterprofile-controller.labels" . | nindent 4 }}
rules:
  {{- include "argocd-clusterprofile-controller.clusterProfileRules" . | nindent 2 }}
{{- end }}
