{{- $cmdParamsConfigMapName := .Values.controller.argoCDCmdParams.configMapName -}}
{{- range $arg := .Values.controller.args -}}
{{- if regexMatch "^--enable-leader-election($|=)" $arg -}}
{{- fail "controller.args must not override the chart-managed --enable-leader-election flag" -}}
{{- end -}}
{{- end -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argocd-clusterprofile-controller.controller.fullname" . }}
  namespace: {{ include "argocd-clusterprofile-controller.namespace" . }}
  labels:
    {{- include "argocd-clusterprofile-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "argocd-clusterprofile-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "argocd-clusterprofile-controller.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.controller.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --metrics-addr=:{{ .Values.controller.metricsPort }}
            - --probe-addr=:{{ .Values.controller.probePort }}
            - --cluster-profile-namespaces={{ include "argocd-clusterprofile-controller.clusterProfileNamespacesArg" . }}
            - --enable-leader-election=true
            {{- if .Values.controller.clusterProfileProvidersFile }}
            - --clusterprofile-provider-file={{ .Values.controller.clusterProfileProvidersFile }}
            {{- end }}
            {{- if .Values.controller.dryRun }}
            - --dry-run
            {{- end }}
            {{- if .Values.controller.debug }}
            - --debug
            {{- end }}
            {{- if .Values.controller.logFormat }}
            - --logformat={{ .Values.controller.logFormat }}
            {{- end }}
            {{- if .Values.controller.logLevel }}
            - --loglevel={{ .Values.controller.logLevel }}
            {{- end }}
            {{- range .Values.controller.args }}
            - {{ . | quote }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.controller.metricsPort }}
              name: metrics
            - containerPort: {{ .Values.controller.probePort }}
              name: healthz
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
          readinessProbe:
            httpGet:
              path: /readyz
              port: healthz
          env:
            {{- if .Values.controller.argoCDCmdParams.enabled }}
            - name: GRPC_ENABLE_TXT_SERVICE_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: {{ $cmdParamsConfigMapName }}
                  key: clusterprofilecontroller.grpc.enable.txt.service.config
                  optional: true
            {{- end }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if .Values.controller.argoCDCmdParams.enabled }}
            - name: ARGOCD_CLUSTERPROFILE_CONTROLLER_DEBUG
              valueFrom:
                configMapKeyRef:
                  key: clusterprofilecontroller.debug
                  name: {{ $cmdParamsConfigMapName }}
                  optional: true
            - name: ARGOCD_CLUSTERPROFILE_CONTROLLER_LOGFORMAT
              valueFrom:
                configMapKeyRef:
                  key: clusterprofilecontroller.log.format
                  name: {{ $cmdParamsConfigMapName }}
                  optional: true
            - name: ARGOCD_CLUSTERPROFILE_CONTROLLER_LOGLEVEL
              valueFrom:
                configMapKeyRef:
                  key: clusterprofilecontroller.log.level
                  name: {{ $cmdParamsConfigMapName }}
                  optional: true
            - name: ARGOCD_LOG_FORMAT_TIMESTAMP
              valueFrom:
                configMapKeyRef:
                  key: log.format.timestamp
                  name: {{ $cmdParamsConfigMapName }}
                  optional: true
            - name: ARGOCD_K8S_CLIENT_QPS
              valueFrom:
                configMapKeyRef:
                  key: clusterprofilecontroller.k8s.client.qps
                  name: {{ $cmdParamsConfigMapName }}
                  optional: true
            - name: ARGOCD_K8S_CLIENT_BURST
              valueFrom:
                configMapKeyRef:
                  key: clusterprofilecontroller.k8s.client.burst
                  name: {{ $cmdParamsConfigMapName }}
                  optional: true
            - name: ARGOCD_K8S_CLIENT_MAX_IDLE_CONNECTIONS
              valueFrom:
                configMapKeyRef:
                  key: clusterprofilecontroller.k8s.client.max.idle.connections
                  name: {{ $cmdParamsConfigMapName }}
                  optional: true
            - name: ARGOCD_K8S_TCP_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  key: clusterprofilecontroller.k8s.tcp.timeout
                  name: {{ $cmdParamsConfigMapName }}
                  optional: true
            - name: ARGOCD_K8S_TCP_KEEPALIVE
              valueFrom:
                configMapKeyRef:
                  key: clusterprofilecontroller.k8s.tcp.keepalive
                  name: {{ $cmdParamsConfigMapName }}
                  optional: true
            - name: ARGOCD_K8S_TLS_HANDSHAKE_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  key: clusterprofilecontroller.k8s.tls.handshake.timeout
                  name: {{ $cmdParamsConfigMapName }}
                  optional: true
            - name: ARGOCD_K8S_TCP_IDLE_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  key: clusterprofilecontroller.k8s.tcp.idle.timeout
                  name: {{ $cmdParamsConfigMapName }}
                  optional: true
            - name: ARGOCD_CLUSTERPROFILE_CONTROLLER_DRY_RUN
              valueFrom:
                configMapKeyRef:
                  key: clusterprofilecontroller.dryrun
                  name: {{ $cmdParamsConfigMapName }}
                  optional: true
            - name: ARGOCD_CLUSTERPROFILE_CONTROLLER_NAMESPACES
              valueFrom:
                configMapKeyRef:
                  key: clusterprofilecontroller.namespaces
                  name: {{ $cmdParamsConfigMapName }}
                  optional: true
            {{- end }}
            {{- with .Values.controller.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.controller.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            {{- if .Values.controller.argoCDCmdParams.enabled }}
            - name: argocd-cmd-params-cm
              mountPath: /home/argocd/params
            {{- end }}
            {{- with .Values.controller.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - emptyDir: {}
          name: tmp
        {{- if .Values.controller.argoCDCmdParams.enabled }}
        - name: argocd-cmd-params-cm
          configMap:
            optional: true
            name: {{ $cmdParamsConfigMapName }}
        {{- end }}
        {{- with .Values.controller.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- range $constraint := . }}
        - {{ toYaml $constraint | nindent 10 | trim }}
          {{- if not (hasKey $constraint "labelSelector") }}
          labelSelector:
            matchLabels:
              {{- include "argocd-clusterprofile-controller.selectorLabels" $ | nindent 14 }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
