{{- if .Values.rbac.create }}
{{- $releaseNamespace := include "argocd-clusterprofile-controller.namespace" . }}
{{- $namespaces := include "argocd-clusterprofile-controller.clusterProfileNamespaces" . | fromJsonArray }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "argocd-clusterprofile-controller.controller.fullname" . }}
  namespace: {{ include "argocd-clusterprofile-controller.namespace" . }}
  labels:
    {{- include "argocd-clusterprofile-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "argocd-clusterprofile-controller.controller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "argocd-clusterprofile-controller.serviceAccountName" . }}
    namespace: {{ include "argocd-clusterprofile-controller.namespace" . }}
{{- if and $namespaces (ne (include "argocd-clusterprofile-controller.watchesAllClusterProfiles" .) "true") }}
{{- range $namespace := $namespaces }}
{{- if ne $namespace $releaseNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "argocd-clusterprofile-controller.controller.fullname" $ }}
  namespace: {{ $namespace }}
  labels:
    {{- include "argocd-clusterprofile-controller.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "argocd-clusterprofile-controller.controller.fullname" $ }}
subjects:
  - kind: ServiceAccount
    name: {{ include "argocd-clusterprofile-controller.serviceAccountName" $ }}
    namespace: {{ include "argocd-clusterprofile-controller.namespace" $ }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
