{{- if and .Values.service.metrics.enabled .Values.service.metrics.serviceMonitor.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "argocd-clusterprofile-controller.controller.fullname" . }}
  namespace: {{ default (include "argocd-clusterprofile-controller.namespace" .) .Values.service.metrics.serviceMonitor.namespace | quote }}
  labels:
    {{- include "argocd-clusterprofile-controller.labels" . | nindent 4 }}
    {{- with .Values.service.metrics.serviceMonitor.selector }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.service.metrics.serviceMonitor.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.metrics.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.service.metrics.serviceMonitor.interval }}
      {{- with .Values.service.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      honorLabels: {{ .Values.service.metrics.serviceMonitor.honorLabels }}
      {{- with .Values.service.metrics.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.service.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.service.metrics.serviceMonitor.scheme }}
      scheme: {{ . }}
      {{- end }}
      {{- with .Values.service.metrics.serviceMonitor.tlsConfig }}
      tlsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ include "argocd-clusterprofile-controller.namespace" . }}
  selector:
    matchLabels:
      {{- include "argocd-clusterprofile-controller.selectorLabels" . | nindent 6 }}
{{- end }}
